
services:
  postgres:
    image: postgres:16
    restart: always
    container_name: novasync_postgres
    environment:
      POSTGRES_USER: sam
      POSTGRES_PASSWORD: sam123
      POSTGRES_DB: novasync
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
